// <auto-generated />
namespace Gameflix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cyberpunk2077Season1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cyberpunk2077Season1));
        
        string IMigrationMetadata.Id
        {
            get { return "202312241858169_Cyberpunk2077Season1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
